#need super user permissions to interact with docker
sudo: required
services:
  - docker

before_install:
  - docker build -t jonpoulter/docker-react -f Dockerfile.dev .

script:
  - docker run jonpoulter/docker-react npm run test -- --coverage